"""
Seed travel data for a Voyager profile via the live API.

Journal entries and trip details are generated by the LLM based on each
character's persona — so each seed run produces unique, varied content.

Usage (backend must be running with the target profile active):
    python scripts/seed.py --profile egwene
    python scripts/seed.py --profile rand
    python scripts/seed.py --profile egwene --trips 4 --entries 5

Profiles are named after characters from the Wheel of Time series.
"""

import argparse
import asyncio
import json
import os
import sys
import httpx
from dotenv import load_dotenv
load_dotenv(override=True)
from openai import AsyncOpenAI

BASE_URL = "http://localhost:8060"

# ── Persona definitions ───────────────────────────────────────────────────────
# These drive LLM generation — no trip data is hardcoded here.

PERSONAS: dict[str, dict] = {
    "egwene": {
        "name": "Egwene",
        "style": (
            "A disciplined, methodical cultural traveller. Pre-books everything months in advance. "
            "Drawn to art history, ceramics, temple architecture, and UNESCO heritage sites. "
            "Takes detailed notes. Prefers depth over breadth — one city for a week over five cities in a week. "
            "Avoids tourist traps; finds satisfaction in planning that pays off."
        ),
        "past_destinations": ["Kyoto, Japan", "Florence, Italy", "Dubrovnik, Croatia"],
        "upcoming_destinations": ["Oaxaca, Mexico"],
        "tags": ["culture", "history", "art", "solo", "planning"],
    },
    "rand": {
        "name": "Rand",
        "style": (
            "An impulsive solo wilderness adventurer. Never books accommodation in advance — things always work out. "
            "Drawn to remote mountains, long treks, and places with no phone signal. "
            "Travels light, hates cities, thrives on chance encounters. "
            "Often ends up somewhere unplanned and finds it was exactly right."
        ),
        "past_destinations": ["Patagonia, Argentina", "Mongolia"],
        "upcoming_destinations": ["Iceland"],
        "tags": ["adventure", "wilderness", "solo", "off-grid", "spontaneous"],
    },
    "nynaeve": {
        "name": "Nynaeve",
        "style": (
            "A slow traveller focused on wellness, nature, and deep rest. "
            "Chooses yoga retreats, forest walks, and coastal villages over cities. "
            "Emotionally present in her journeys — notices small things, connects with locals. "
            "Avoids rush and noise. Often travels solo but connects warmly with people she meets."
        ),
        "past_destinations": ["Ubud, Bali", "Scottish Highlands"],
        "upcoming_destinations": ["Kerala, India"],
        "tags": ["wellness", "nature", "slow-travel", "solo"],
    },
    "mat": {
        "name": "Mat",
        "style": (
            "A spontaneous traveller drawn to nightlife, festivals, street food, and lucky accidents. "
            "Never has a plan. Ends up in the right place at the right time through sheer luck. "
            "Loves card games, live music, cheap eats, and talking to strangers in bars. "
            "Journals are short, vivid, and usually involve something going hilariously wrong or right."
        ),
        "past_destinations": ["New Orleans, USA", "Bangkok, Thailand"],
        "upcoming_destinations": ["Lisbon, Portugal"],
        "tags": ["nightlife", "festivals", "food", "spontaneous", "solo"],
    },
    "perrin": {
        "name": "Perrin",
        "style": (
            "A quiet, deliberate traveller who prefers forests, small towns, and long walks to cities and crowds. "
            "Notices animals, landscape, and the pace of rural life. "
            "Stays in family-run guesthouses. Rarely takes photos — prefers to just be there. "
            "Journals are sparse but observant, often about a single moment rather than a full day."
        ),
        "past_destinations": ["Black Forest, Germany", "Vermont, USA"],
        "upcoming_destinations": ["Hokkaido, Japan"],
        "tags": ["hiking", "nature", "forests", "small-towns", "solo"],
    },
    "lan": {
        "name": "Lan",
        "style": (
            "A solo traveller drawn to remote, austere, and physically demanding destinations. "
            "Long treks with no guides, minimal gear, harsh weather. Comfortable with silence and isolation. "
            "Writes sparse, precise journal entries — one or two observations per day, no self-pity. "
            "Never complains, never turns back. Finds meaning in endurance."
        ),
        "past_destinations": ["Faroe Islands", "Kyrgyzstan"],
        "upcoming_destinations": ["Northern Norway"],
        "tags": ["remote", "trekking", "solo", "austere", "off-grid"],
    },
    "moiraine": {
        "name": "Moiraine",
        "style": (
            "A deeply knowledgeable solo traveller obsessed with ancient history, archaeology, and forgotten civilisations. "
            "Arrives knowing more about a site than the guides do. Seeks out archives, museum back-rooms, and local historians. "
            "Journal entries read like field notes — precise, layered, intellectually curious. "
            "Travels with purpose and never wastes time on things that don't matter."
        ),
        "past_destinations": ["Petra, Jordan", "Luxor, Egypt"],
        "upcoming_destinations": ["Cappadocia, Turkey"],
        "tags": ["history", "archaeology", "ancient-ruins", "solo"],
    },
}

# ── LLM generation ────────────────────────────────────────────────────────────

GENERATION_PROMPT = """\
You are generating realistic travel data for a travel journal app called Voyager.

Generate data for the character described below. Return a JSON object with this exact structure:

{{
  "trips": [
    {{
      "destination": "City, Country",
      "dates": "Month YYYY",
      "status": "past" | "upcoming",
      "emoji": "<single travel emoji>",
      "summary": "<1-2 sentence trip summary in the character's voice>",
      "tags": ["tag1", "tag2"],
      "journal_entries": [
        {{
          "date": "YYYY-MM-DD",
          "body": "<journal entry, 3-6 sentences, written in first person in the character's voice>"
        }}
      ]
    }}
  ]
}}

Rules:
- Past trips should have {entries_per_trip} journal entries each. Upcoming trips have zero journal entries.
- Journal entries should feel personal and specific — real observations, not generic travel writing.
- Dates for past trips should be realistic (2023-2025). Upcoming trips should be in 2026.
- Journal entry dates should be consecutive days within the trip's month/year.
- Emoji should suit the destination and vibe, not just be a globe.
- Respond with JSON only — no prose, no markdown fences.

Character: {name}
Travel style: {style}
Past destinations to use: {past_destinations}
Upcoming destinations to use: {upcoming_destinations}
Default tags: {tags}
"""


async def generate_profile_data(persona: dict, entries_per_trip: int) -> list[dict]:
    client = AsyncOpenAI(
        api_key=os.environ["OPENROUTER_API_KEY"],
        base_url="https://openrouter.ai/api/v1",
    )
    model = os.environ.get("OPENROUTER_MODEL", "anthropic/claude-haiku-4-5")

    prompt = GENERATION_PROMPT.format(
        name=persona["name"],
        style=persona["style"],
        past_destinations=", ".join(persona["past_destinations"]),
        upcoming_destinations=", ".join(persona["upcoming_destinations"]),
        tags=", ".join(persona["tags"]),
        entries_per_trip=entries_per_trip,
    )

    print(f"  Generating data for {persona['name']} via {model}...")
    response = await client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.9,
    )
    raw = (response.choices[0].message.content or "").strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()
    data = json.loads(raw)
    return data["trips"]


# ── Seeding ───────────────────────────────────────────────────────────────────

async def seed_profile(profile: str, base_url: str, entries_per_trip: int) -> None:
    persona = PERSONAS.get(profile)
    if not persona:
        print(f"Unknown profile: {profile}. Available: {', '.join(PERSONAS)}")
        sys.exit(1)

    trips = await generate_profile_data(persona, entries_per_trip)

    async with httpx.AsyncClient(base_url=base_url, timeout=30) as client:
        try:
            r = await client.get("/health")
            r.raise_for_status()
        except Exception as e:
            print(f"Backend not reachable at {base_url}: {e}")
            sys.exit(1)

        print(f"Seeding profile '{profile}' → {base_url}")

        for trip_data in trips:
            journal_entries = trip_data.pop("journal_entries", [])

            r = await client.post("/api/trips", json=trip_data)
            r.raise_for_status()
            trip = r.json()
            trip_id = trip["id"]
            print(f"  ✓ Trip: {trip['emoji']} {trip['destination']} ({trip['status']})")

            for entry in journal_entries:
                r = await client.post(
                    f"/api/trips/{trip_id}/journal",
                    json={"date": entry["date"], "body": entry["body"], "source": "app"},
                )
                r.raise_for_status()
                print(f"      ✓ Journal entry: {entry['date']}")

        total_entries = sum(len(t.get("journal_entries", [])) for t in trips)
        print(f"\nDone. {persona['name']} profile seeded with {len(trips)} trip(s), {total_entries} journal entries.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed a Voyager profile with LLM-generated travel data.")
    parser.add_argument("--profile", required=True, choices=list(PERSONAS), help="Profile name")
    parser.add_argument("--base-url", default=BASE_URL, help=f"API base URL (default: {BASE_URL})")
    parser.add_argument("--entries", type=int, default=4, dest="entries_per_trip",
                        help="Journal entries to generate per past trip (default: 4)")
    args = parser.parse_args()
    asyncio.run(seed_profile(args.profile, args.base_url, args.entries_per_trip))


if __name__ == "__main__":
    main()
