"""add_area_to_saved_places

Revision ID: 66ab624754ee
Revises: 690d95eed875
Create Date: 2026-07-01 11:46:28.927394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ab624754ee'
down_revision: Union[str, None] = '690d95eed875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_places', sa.Column('area', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_places', 'area')
    # ### end Alembic commands ###
