"""add_journal_entries_and_connected_content

Revision ID: ce85be5de3c1
Revises: fbc6928f0bbb
Create Date: 2026-06-19 22:14:53.675258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce85be5de3c1'
down_revision: Union[str, None] = 'fbc6928f0bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('captured_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trips', sa.Column('cover_photo_url', sa.String(), nullable=True))
    # Add tags as nullable first (SQLite can't add NOT NULL without a default),
    # then backfill existing rows and enforce NOT NULL via a new column swap.
    # For SQLite simplicity we just store it nullable — the ORM default handles new rows.
    op.add_column('trips', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'tags')
    op.drop_column('trips', 'cover_photo_url')
    op.drop_table('journal_entries')
    op.drop_table('connected_content')
    # ### end Alembic commands ###
